### PR TITLE
Test: pathPrefix initialization :/

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to
- https://github.com/GSA/data.gov/issues/4033

Changes:
- Update footer links to be relative to current site (not external links)
- Change default pagination generation for topics/updates (start at 1, not at null)
  - ~Redirect `updates` to `updates/1`~ (This doesn't work ... at least right now)
  - Redirect `climate` to `climate/1`
  - Redirect `maritime` to `maritime/1`
- Remove preceding `/` from post `permalinks`
- Fix relative page calls from parent to child pages
- Fix cypress tests based on new functionality
- Don't test accessibility on external touchpoints form

References:
- https://www.11ty.dev/docs/filters/url/

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
It is doing what I want it to do, but it seems like the prefixPath is not effecting link creations 😕 

image

**Review by btylerburton — DISMISSED** [review]

**Comment by btylerburton** [comment]
Looks good. 

Do we need a new prefix for federalist build? 

I'll hold off to merge in case you've got a11y fixes coming.

**Comment by nickumia-reisys** [comment]
@btylerburton Federalist automatically sets the `prefix` for the staging build. 

I do have to fix the cypress tests, but I guess I was just looking for validation from someone else that I didn't miss anything in the preview.

**Comment by nickumia-reisys** [comment]
Tests work locally, so just debugging GH

image

**Review by robert-bryson — APPROVED** [review]

**Comment by nickumia-reisys** [comment]
Only two things are known to be broken on the staging site:
- "Back to" topic
- Updates on the homepage

**Pull request merged**
