### PR TITLE
Updates static site for new layout

### PR DESCRIPTION
**Pull request by btylerburton**
Related to:
- https://github.com/GSA/data.gov/issues/4181

Changes:
- Updates USWDS to v3.x
- Adds new index template
- updates 11ty config
- updates styles to remove unneeded defaults

Caveats:
- Cypress tests are all commented out and will need to be rewritten and turned as layout is finalized.

### CODE REVIEW

**Comment by btylerburton** [comment]
There are A LOT of changes in this PR, but let me break down the big ones:

- Updated the eleventyConfig & asset pipeline scripts to reflect updates in the parent repo: https://github.com/cloud-gov/pages-uswds-11ty
- USWDS 3.x allows for you to only specify changes to defaults, so a lot of the setting of tokens is done automatically, hence the removal of many `.scss` files
- I moved all `.md` content files to either `pages` or `posts` directory based on what type of entry they were. This cleans up the file system, and allows for more defined layout inheritance

**Comment by nickumia-reisys** [comment]
A few questions about the UI,

Is the background image okay?  It seems stretched and also repeated.
image

User guide twice?
image

Do we have different fonts?
image

Is this supposed to be an external link?
image

These were all minor things, but overall, the site seems just as functional as before.  I think we need a link to "updates" or "blogs" somewhere, so that that data is not completely orphaned.  If this is ready for review, I can approve it after the above questions 👍

**Comment by btylerburton** [comment]
Great questions @nickumia-reisys. I would not consider this a final pass. I mostly just wanted to get an incremental build out so I wasn't holding onto the work. That said, let me try to answer your questions.

> Is the background image okay? It seems stretched and also repeated.

Probably. I'll take a look. More than likely just a change to CSS `background-size`.

> User guide twice?

That was a mistake. Should have that hidden.

> Do we have different fonts?

Probably. Will take a look.

> Is this supposed to be an external link?

Now that you mention it... yes!

**Review by nickumia-reisys — APPROVED** [review]
🐺

**Pull request merged**
