### PR TITLE
Adds new banner and section for 15yr anniversary

### PR DESCRIPTION
**Pull request by btylerburton**
## Changes proposed in this pull request:
- adds new banner and section for datagov 15yr anniversary
-
-

## security considerations
[Note the any security considerations here, or make note of why there are none]

### CODE REVIEW

**Comment by rshewitt** [comment]
do we want to center the anniversary section similar to mission for ~medium sized devices? 
Screenshot 2024-05-20 at 3 35 08 PM

**Comment by btylerburton** [comment]
@hkdctol any opinions on the text centering? I prefer it left flush personally.

**Comment by btylerburton** [comment]
Screenshot 2024-05-20 at 4 51 51 PM
this is what it would look like

**Comment by btylerburton** [comment]
After seeing that, I'm kind of warming up to the centered text.

**Comment by hkdctol** [comment]
It looks like in the figma the rest of the content is also centered for tablet view? Consistency would be good

**Comment by btylerburton** [comment]
Alright. Page is updated. @hkdctol and @rshewitt take a look.

**Comment by hkdctol** [comment]
@btylerburton I think you added the hyperlink to the wrong place--the Congress.gov link is to the OPEN Government Data Act--there was already a valid link to the 2013 Open data policy, which was a digital.gov link

**Comment by btylerburton** [comment]
Aha, yeah. All clear now. Preview link is fixed @hkdctol

**Comment by rshewitt** [comment]
looks good!

**Comment by hkdctol** [comment]
Looks good to go!

**Review by rshewitt — APPROVED** [review]

**Pull request merged**
