### PR TITLE
4726 ga4 metrics

### PR DESCRIPTION
**Pull request by robert-bryson**
Related to https://github.com/GSA/data.gov/issues/4726
## Changes proposed in this pull request:
-
-
-

## security considerations
[Note the any security considerations here, or make note of why there are none]

### CODE REVIEW

**Comment by btylerburton** [comment]
This is an interim solution to get us to the demo next week. More robust system should be delivered shortly.

**Review by jbrown-xentity — APPROVED** [review]
Looks pretty good! Is this something we want to actually merge in it's current state, or use the preview link to demo?

**Comment by btylerburton** [comment]
Let me ask cg-pages support how long those builds last. Otherwise, team was fine with merging in since it has that disclaimer at top.

**Comment by btylerburton** [comment]
cg-pages says they never expire, so I'll leave this up to @tdlowden when he gets back on Monday.

**Pull request merged**
