### PR TITLE
Styling - Homepage + Climate Homepage

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to 
- https://github.com/GSA/data.gov/issues/3891

Changes/New Additions:
- Remove extra whitespace at the top and bottom of each page.
- Add links to the homepage to topics.
- Reorganize bootstrap include from `tools.html` to `meta.html` to be used everywhere in the static site.
- Remove remaining local images

References:
- https://getbootstrap.com/docs/4.0/components/carousel/
- https://getbootstrap.com/docs/4.0/components/card/

### CODE REVIEW

**Comment by nickumia-reisys** [comment]
### Current home page look
image

**Comment by nickumia-reisys** [comment]
### Current Climate Topic Page
climate

**Comment by btylerburton** [comment]
Do you know the URL for the climate page in the federalist build?

**Comment by btylerburton** [comment]
Nice improvements! IMO some sort of grid layout would work better than a carousel for the climate topics, but that's the only feedback I've got. Curious what the rest of the team thinks.

**Comment by nickumia-reisys** [comment]
Climate test link: https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/preview/gsa/datagov-11ty/whitespace-styling/climate/
Homepage test link: https://federalist-2ac784db-2321-4734-8d02-933835d88304.app.cloud.gov/preview/gsa/datagov-11ty/whitespace-styling/

**Review by Jin-Sun-tts — APPROVED** [review]

**Pull request merged**
